"""Update schema to match assignment diagram

Revision ID: 851b3fbd0042
Revises: cd7025612045
Create Date: 2026-04-03 00:21:06.898169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '851b3fbd0042'
down_revision: Union[str, Sequence[str], None] = 'cd7025612045'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('account', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('account', sa.Column('role_id', sa.Integer(), nullable=False))
    op.add_column('account', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('account', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_foreign_key(None, 'account', 'role', ['role_id'], ['id'])
    op.create_foreign_key(None, 'account', 'user', ['user_id'], ['id'])
    op.add_column('event', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('event', sa.Column('quota', sa.Integer(), nullable=False))
    op.add_column('event', sa.Column('started_at', sa.DateTime(), nullable=False))
    op.add_column('event', sa.Column('ended_at', sa.DateTime(), nullable=False))
    op.add_column('event', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('event', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_column('event', 'date')
    op.drop_column('event', 'location')
    op.drop_column('event', 'title')
    op.drop_column('registration', 'registration_date')
    op.add_column('user', sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column('user', sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('user', sa.Column('whatsapp', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False))
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_constraint(op.f('user_account_id_fkey'), 'user', type_='foreignkey')
    op.drop_column('user', 'account_id')
    op.drop_column('user', 'name')
    op.drop_column('user', 'occupation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('occupation', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('user_account_id_fkey'), 'user', 'account', ['account_id'], ['id'])
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    op.drop_column('user', 'whatsapp')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.add_column('registration', sa.Column('registration_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('event', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('event', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('event', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('event', 'updated_at')
    op.drop_column('event', 'created_at')
    op.drop_column('event', 'ended_at')
    op.drop_column('event', 'started_at')
    op.drop_column('event', 'quota')
    op.drop_column('event', 'name')
    op.drop_constraint(None, 'account', type_='foreignkey')
    op.drop_constraint(None, 'account', type_='foreignkey')
    op.drop_column('account', 'updated_at')
    op.drop_column('account', 'created_at')
    op.drop_column('account', 'role_id')
    op.drop_column('account', 'user_id')
    op.drop_table('log')
    # ### end Alembic commands ###
